### ISSUE TITLE
make does not work smoothly

### ISSUE THREAD

**Issue by hassaan4584** [ClickerMonkey/CDSL#1]
When i run make command, it throws the following error.

![screen shot 2017-04-08 at 7 01 54 pm](https://cloud.githubusercontent.com/assets/5270282/24829590/3b706966-1c8e-11e7-9564-22e32b2ca969.png)

Since I did not need the polygon.h and plane.h files, so I deleted the entries of both the files from the file "makefile"*. After that i ran the "make" command again, and it compiled successfully.

*open "makefile" in any text editor.

**Comment by ClickerMonkey** [comment]
Thanks - looks like I never committed the polygon code!
